version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto_trades
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped 